"""Generate synthetic sample files for dashboard4dx.

Run this once to (re)create the sample files in this directory:
    python sample_data/generate_samples.py

Filename conventions match real-world inputs:
- Function master / WBS / defect tracker exports: plain filenames (no timestamp).
- Test counts / Code line counts: filenames carry a `_YYYYMMDDhhmmss` snapshot
  stamp because those are auto-generated by tools and the dashboard uses the
  stamp to organize history for trend analysis.

All data is fictional. No real project information is included.
"""
from __future__ import annotations

import csv
import random
from datetime import date, timedelta
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

random.seed(20260420)

OUT_DIR = Path(__file__).resolve().parent

# ----- Function ID master -----------------------------------------------------
# Real-world format: 1–10 ASCII letters + 1–10 ASCII digits, no separators.
# A few IDs intentionally appear twice with different names (the spec allows
# duplicate Function IDs with different Function names).
FUNCTION_ENTRIES: list[tuple[str, str]] = [
    ("AUTH001",  "User Login"),
    ("AUTH002",  "User Registration"),
    ("AUTH003",  "Password Reset"),
    ("USER010",  "Profile Edit"),
    ("USER020",  "Profile Edit (Admin)"),
    ("SEARCH01", "Search (Basic)"),
    ("SEARCH01", "Search (Advanced)"),     # duplicate ID, different name
    ("CART001",  "Cart Add"),
    ("CART002",  "Cart Remove"),
    ("ORD001",   "Checkout"),
    ("PAY001",   "Payment - Credit Card"),
    ("PAY001",   "Payment - Bank Transfer"),  # duplicate ID, different name
    ("ORD010",   "Order History"),
    ("NOTIFY01", "Notification - Email"),
    ("NOTIFY02", "Notification - Push"),
    ("SYNC001",  "Settings Sync"),
    ("EXP001",   "Data Export"),
    ("IMP001",   "Data Import"),
    ("AUDIT01",  "Audit Log"),
    ("ADM001",   "Admin Dashboard"),
]

UNIQUE_IDS = sorted({fid for fid, _ in FUNCTION_ENTRIES})


# ----- 1. Function master xlsx ------------------------------------------------
def make_function_master() -> Path:
    """Build a master xlsx that exercises the loader's tricky cases:
      - Section-header rows (col B filled, col F empty) interspersed in data
      - A trailing 'Total' row (col B filled, col F empty) past the last entry
      - Strike-through formatting on one row (must NOT be excluded)
      - Duplicate Function IDs with different names
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "機能一覧"
    headers = ["No", "Category", "Subsystem", "Owner", "Status",
               "機能ID", "機能名称", "Notes"]
    for col_idx, h in enumerate(headers, start=1):
        ws.cell(row=1, column=col_idx, value=h).font = Font(bold=True)

    # Insert a section header before these IDs (B filled, F empty).
    section_breaks = {"SEARCH01": "--- Search & Discovery ---",
                      "PAY001":   "--- Payment ---"}

    row_cursor = 2
    seq = 1
    for fid, fname in FUNCTION_ENTRIES:
        if fid in section_breaks and not any(
            ws.cell(row=r, column=2).value == section_breaks[fid]
            for r in range(2, row_cursor)
        ):
            # B filled, F empty → loader must skip and continue
            ws.cell(row=row_cursor, column=2, value=section_breaks[fid])
            row_cursor += 1

        ws.cell(row=row_cursor, column=1, value=seq); seq += 1
        ws.cell(row=row_cursor, column=2,
                value=random.choice(["Auth", "User", "Order", "Notify", "Admin"]))
        ws.cell(row=row_cursor, column=3,
                value=random.choice(["Web", "API", "Worker"]))
        ws.cell(row=row_cursor, column=4,
                value=random.choice(["alice", "bob", "carol", "dave"]))
        ws.cell(row=row_cursor, column=5,
                value=random.choice(["Active", "Active", "Active", "Deprecated"]))
        ws.cell(row=row_cursor, column=6, value=fid)
        ws.cell(row=row_cursor, column=7, value=fname)

        if fid == "AUDIT01":
            for col_idx in range(1, 9):
                ws.cell(row=row_cursor, column=col_idx).font = Font(strike=True)
        row_cursor += 1

    # A blank-ish gap, then a trailing 'Total' row (B filled, F empty)
    row_cursor += 2
    ws.cell(row=row_cursor, column=2, value="Total")

    out = OUT_DIR / "function_master.xlsx"
    wb.save(out)
    return out


# ----- 2. WBS xlsm ------------------------------------------------------------
# Sub-task label pool. The keyword-bearing labels are what the role
# analytics section keys on (プログラム開発 / テスト仕様書作成 / テスト実施);
# mixed in with a handful of non-keyword labels for realism. Each tuple is
# (label, role) where role is the key in ROLE_ASSIGNEES below; role=None
# means the label doesn't map to any analytics role (still rendered on the
# Gantt, just not in the 担当者×ロール views).
WBS_SUBTASK_POOL: list[tuple[str, object]] = [
    ("詳細設計",                     None),
    ("コードレビュー",                None),
    ("プログラム開発",                "dev"),
    ("プログラム開発（リファクタ）",  "dev"),
    ("テスト仕様書作成",              "test_spec"),
    ("テスト仕様書作成（正常系）",    "test_spec"),
    ("テスト仕様書作成（異常系）",    "test_spec"),
    ("テスト実施",                    "test_exec"),
    ("単体テスト実施",                "test_exec"),
    ("結合テスト実施",                "test_exec"),
]

# Rough role specialization so the analytics output has a readable pattern
# (a name tends to own either dev or test work across features). Keep the
# pools overlapping a bit — real teams aren't strictly siloed.
WBS_ROLE_ASSIGNEES: dict[object, list[str]] = {
    "dev":       ["田中", "佐藤", "高橋", "伊藤"],
    "test_spec": ["鈴木", "小林", "田中"],
    "test_exec": ["渡辺", "中村", "小林", "佐藤"],
    None:        ["田中", "佐藤", "鈴木", "渡辺", "高橋"],
}

# Demo-specific assignee pools used *only* on specific Function IDs so the
# bubble map exercises the two edge rendering cases:
#   - CLEAN_ONLY: features in `CLEAN_FIDS` never get defects, so these
#     assignees end up with defect_total = 0 and showcase the
#     marker.sizemin floor that keeps zero-defect bubbles visible.
#   - NO_EXEC_ONLY: features in `NO_EXEC_FIDS` have 実施済 = 0 so
#     incident_rate is NaN for every feature they touch, showcasing the
#     "NaN → 0% fallback with `—` hover value" path.
WBS_CLEAN_ONLY_ASSIGNEES: dict[object, list[str]] = {
    "dev":       ["福田"],
    "test_spec": ["清水"],
    "test_exec": ["松本"],
    None:        ["福田"],
}
WBS_NO_EXEC_ONLY_ASSIGNEES: dict[object, list[str]] = {
    "dev":       ["吉田"],
    "test_spec": ["石川"],
    "test_exec": ["堀"],
    None:        ["吉田"],
}
# Function IDs reserved for the two demo scenarios above. These are excluded
# from the defects generator (CLEAN_FIDS) and get 実施済 = 0 in test counts
# (NO_EXEC_FIDS) respectively.
CLEAN_FIDS   = {"AUDIT01", "ADM001", "SYNC001"}
NO_EXEC_FIDS = {"IMP001", "EXP001"}

# Chance that a sub-task row's 担当者 (N column) is left blank — surfaces as
# 「（未割当）」in the analytics and exercises that fallback path.
WBS_UNASSIGNED_PROB = 0.15


def _write_percent(ws, coord: str, pct: int) -> None:
    """Write an Excel percent-formatted cell: underlying value is fractional
    (0..1) and the display format is ``0%``. This matches how real WBS tools
    store progress columns, so the loader's percent-normalization path is
    exercised by the sample too."""
    cell = ws[coord]
    cell.value = pct / 100.0
    cell.number_format = "0%"


def _fmt_md(d):
    """Format a date as ``MM/DD`` — matches the real WBS convention where
    per-task dates omit the year and the phase anchors on row 6 (J6 / N6)
    carry the absolute 年/月/日 so the year can be reconstructed."""
    if d is None:
        return None
    return f"{d.month:02d}/{d.day:02d}"


def make_wbs() -> Path:
    """Build a WBS that mimics the real format: data starts row 16, Function ID
    appears as '機能ID：XXXX' somewhere in cols E–I, key columns at P/Q/R/S/T/U/V/AA.

    Some Function IDs also carry sub-task breakdown rows: rows *without* a
    Function ID where L column is "●" (fixed marker). In those rows:
      - the column right of the parent's Function ID column holds a task
        label (プログラム開発 / テスト仕様書作成 / テスト実施 / レビューなど);
      - P..V/AA carry the sub-task's own schedule;
      - **N column carries the 担当者** — consumed by the Charts tab's
        担当者×ロール analytics to attribute each role to a person.
    A small fraction of sub-tasks are intentionally left unassigned (empty
    N) so the '（未割当）' fallback is exercised by the sample too.

    For exercising loader behavior the sample also includes a small number
    of intentionally-skipped shapes:
      - A duplicate Function ID row after its first valid occurrence (should
        be skipped by the loader; by default its following ● rows also skip).
      - A row with no Function ID and no ● in L (a noise / spacer row, also
        skipped — exercises the "●-gated" sub-task filter).
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "メイン"

    # Rows 1-15: arbitrary header / metadata noise
    ws["A1"] = "WBS Sample"
    ws["A2"] = "Generated for dashboard4dx demo"
    # Phase anchors (row 6). Real WBS files store the phase start/end here
    # as 年/月/日; per-task dates (Q/R/S/T) are written later as 月/日 only
    # and the loader resolves the year from this window.
    phase_start = date(2026, 1, 1)
    phase_end = date(2026, 5, 31)
    ws["I6"] = "期間"
    ws["J6"] = phase_start.strftime("%Y/%m/%d")
    ws.merge_cells("J6:L6")
    ws["M6"] = "〜"
    ws["N6"] = phase_end.strftime("%Y/%m/%d")
    ws.merge_cells("N6:O6")
    ws["A14"] = "Section"
    ws["E14"] = "Phase / Function"
    ws["L14"] = "●印"
    ws["P14"] = "予定工数"
    ws["Q14"] = "開始予定日"
    ws["R14"] = "終了予定日"
    ws["S14"] = "開始実績日"
    ws["T14"] = "終了実績日"
    ws["U14"] = "投入工数"
    ws["V14"] = "実績進捗率"
    ws["AA14"] = "計画進捗率"

    # ~40% of Function IDs get sub-task breakdowns so both patterns appear.
    # ~70% of Function IDs get sub-task breakdowns — higher than strictly
    # realistic, but the Charts-tab 担当者×ロール analytics needs enough
    # coverage in the demo file to produce a legible heatmap / table.
    with_subs = set(random.sample(UNIQUE_IDS,
                                  k=max(3, int(len(UNIQUE_IDS) * 0.7))))

    today = date(2026, 4, 20)
    row = 16
    for fid in UNIQUE_IDS:
        # Sprinkle the Function ID across one of cols E..I randomly,
        # using one of three accepted formats. Keep sub-col <= J by capping
        # the parent column at H when we know we'll emit sub-tasks.
        cols = ["E", "F", "G", "H"] if fid in with_subs else ["E", "F", "G", "H", "I"]
        target_col = random.choice(cols)
        sub_col = chr(ord(target_col) + 1)  # column immediately right of parent
        fmt = random.choice([f"機能ID：{fid}", f"機能ID:{fid}", fid])
        ws[f"A{row}"] = "Feature"
        ws[f"{target_col}{row}"] = fmt

        planned_effort = round(random.uniform(5, 40), 1)
        actual_effort = round(planned_effort * random.uniform(0.6, 1.3), 1)
        start_plan = today - timedelta(days=random.randint(20, 80))
        end_plan = start_plan + timedelta(days=random.randint(5, 30))
        start_actual = start_plan + timedelta(days=random.randint(-3, 5))
        # 25% of items are still in flight: no actual end date
        end_actual = (end_plan + timedelta(days=random.randint(-3, 10))
                      if random.random() > 0.25 else None)
        actual_pct = (random.randint(70, 100)
                      if end_actual else random.randint(10, 70))
        planned_pct = random.randint(60, 100)

        ws[f"P{row}"] = planned_effort
        ws[f"Q{row}"] = _fmt_md(start_plan)
        ws[f"R{row}"] = _fmt_md(end_plan)
        ws[f"S{row}"] = _fmt_md(start_actual)
        ws[f"T{row}"] = _fmt_md(end_actual)
        ws[f"U{row}"] = actual_effort
        _write_percent(ws, f"V{row}", actual_pct)
        _write_percent(ws, f"AA{row}", planned_pct)
        row += 1

        if fid not in with_subs:
            continue

        # Every feature with sub-tasks gets one row per analytics role so
        # the Charts-tab role views are populated; plus a 50/50 prefix
        # row (設計 or レビュー — no role keyword) for realism. Order is
        # roughly dev → test_spec → test_exec so the schedule slices flow.
        subs: list[tuple[str, object]] = []
        if random.random() < 0.5:
            subs.append(random.choice(
                [p for p in WBS_SUBTASK_POOL if p[1] is None]
            ))
        for role_key in ("dev", "test_spec", "test_exec"):
            subs.append(random.choice(
                [p for p in WBS_SUBTASK_POOL if p[1] == role_key]
            ))

        n_subs = len(subs)
        total_days = max(n_subs, (end_plan - start_plan).days)
        chunk = total_days // n_subs
        remaining_effort = planned_effort
        remaining_actual = actual_effort
        for i, (sub_label, role_key) in enumerate(subs):
            s_start_plan = start_plan + timedelta(days=i * chunk)
            s_end_plan = (end_plan if i == n_subs - 1
                          else start_plan + timedelta(days=(i + 1) * chunk - 1))
            s_start_actual = s_start_plan + timedelta(days=random.randint(-2, 3))
            # Last sub-task inherits the parent's in-flight status roughly
            in_flight = (end_actual is None and i == n_subs - 1) or random.random() < 0.15
            s_end_actual = (None if in_flight
                            else s_end_plan + timedelta(days=random.randint(-2, 4)))
            share = (1.0 / (n_subs - i)) if i < n_subs - 1 else 1.0
            s_planned_effort = round(remaining_effort * share, 1)
            s_actual_effort = round(remaining_actual * share, 1)
            remaining_effort -= s_planned_effort
            remaining_actual -= s_actual_effort

            # Pick 担当者 from the role pool so a name tends to own either
            # dev or test work consistently. Blank ~15% of the time to
            # exercise the (未割当) surface in the analytics.
            #
            # Features flagged as CLEAN_FIDS or NO_EXEC_FIDS route to
            # dedicated assignee pools so those people end up with
            # defect_total = 0 or incident_rate = NaN respectively —
            # exercises the bubble-map edge cases on-screen.
            if random.random() < WBS_UNASSIGNED_PROB:
                assignee = ""
            elif fid in CLEAN_FIDS:
                assignee = random.choice(
                    WBS_CLEAN_ONLY_ASSIGNEES[role_key])
            elif fid in NO_EXEC_FIDS:
                assignee = random.choice(
                    WBS_NO_EXEC_ONLY_ASSIGNEES[role_key])
            else:
                assignee = random.choice(WBS_ROLE_ASSIGNEES[role_key])

            ws[f"A{row}"] = "Task"
            ws[f"L{row}"] = "●"
            ws[f"N{row}"] = assignee
            ws[f"{sub_col}{row}"] = sub_label
            ws[f"P{row}"] = s_planned_effort
            ws[f"Q{row}"] = _fmt_md(s_start_plan)
            ws[f"R{row}"] = _fmt_md(s_end_plan)
            ws[f"S{row}"] = _fmt_md(s_start_actual)
            ws[f"T{row}"] = _fmt_md(s_end_actual)
            ws[f"U{row}"] = s_actual_effort
            _write_percent(ws, f"V{row}",
                           random.randint(70, 100) if s_end_actual
                           else random.randint(10, 70))
            _write_percent(ws, f"AA{row}", random.randint(60, 100))
            row += 1

    # ----- Loader edge-cases ---------------------------------------------------
    # A noise / spacer row with no Function ID and no ● marker. The loader
    # must skip this (sub-task candidacy is gated on L="●").
    ws[f"A{row}"] = "(note)"
    ws[f"F{row}"] = "※ 以下は重複機能IDのテストケース"
    row += 1

    # Duplicate Function ID: AUTH001 appears again well below its first
    # occurrence. The loader keeps only the first; this row and its ● rows
    # below are skipped (default). With the "attach_after_dup" setting ON,
    # the ● rows re-attach to the previously valid parent instead of dying.
    dup_fid = "AUTH001"
    ws[f"A{row}"] = "Feature"
    ws[f"G{row}"] = f"機能ID:{dup_fid}"
    ws[f"P{row}"] = 12.3
    ws[f"Q{row}"] = _fmt_md(date(2026, 4, 15))
    ws[f"R{row}"] = _fmt_md(date(2026, 4, 25))
    ws[f"S{row}"] = _fmt_md(date(2026, 4, 15))
    ws[f"U{row}"] = 8.0
    _write_percent(ws, f"V{row}", 55)
    _write_percent(ws, f"AA{row}", 70)
    row += 1
    for sub in ("追加レビュー", "追加修正"):
        ws[f"A{row}"] = "Task"
        ws[f"L{row}"] = "●"
        ws[f"H{row}"] = sub  # sub_col = G+1 = H
        ws[f"P{row}"] = 6.0
        ws[f"Q{row}"] = _fmt_md(date(2026, 4, 15))
        ws[f"R{row}"] = _fmt_md(date(2026, 4, 20))
        ws[f"S{row}"] = _fmt_md(date(2026, 4, 15))
        ws[f"U{row}"] = 4.0
        _write_percent(ws, f"V{row}", 40)
        _write_percent(ws, f"AA{row}", 60)
        row += 1

    # Save as .xlsm — openpyxl can write the file with a macro-enabled extension
    # even without an actual VBA project; the loader reads it just fine.
    out = OUT_DIR / "wbs.xlsm"
    wb.save(out)
    return out


# ----- 3. Defect tracker CSV --------------------------------------------------
def make_defects() -> Path:
    out = OUT_DIR / "defects.csv"
    trackers = ["不具合管理", "課題管理", "不具合管理", "不具合管理", "タスク"]
    statuses = ["新規", "対応中", "解決", "却下", "再発"]
    # Skewed weights: 実装ミス は少し多め、性能/セキュリティ系はレア
    # — donut + Top-N table がそれっぽく見えるバランスにしておく。
    classes_weighted = [
        ("実装ミス", 6),
        ("仕様漏れ", 4),
        ("設計不備", 4),
        ("環境起因", 3),
        ("再現不可", 3),
        ("性能問題", 2),
        ("セキュリティ起因", 1),
    ]
    classes = [c for c, w in classes_weighted for _ in range(w)]
    assignees = ["alice", "bob", "carol", "dave", "ellen"]

    today = date(2026, 4, 20)
    # CLEAN_FIDS never receive defects — by construction, any assignee
    # who only works on those features ends up with defect_total = 0
    # and demos the marker.sizemin floor in the bubble map.
    defect_eligible_fids = [f for f in UNIQUE_IDS if f not in CLEAN_FIDS]
    rows = []
    for i in range(80):
        fid = random.choice(defect_eligible_fids)
        tracker = random.choice(trackers)
        status = random.choice(statuses)
        start = today - timedelta(days=random.randint(1, 120))
        # 35% have no actual end date (unresolved)
        end = (start + timedelta(days=random.randint(1, 30))
               if random.random() > 0.35 else None)
        # Defect tracker exports dates in MM/DD/YYYY (US-style).
        rows.append({
            "トラッカー": tracker,
            "ステータス": status,
            "担当者": random.choice(assignees),
            "実開始日": start.strftime("%m/%d/%Y"),
            "実終了日": end.strftime("%m/%d/%Y") if end else "",
            "機能ID": fid,
            "問題分類": random.choice(classes),
        })

    # Real exports are usually CP932; we write UTF-8 with BOM here for editor
    # convenience, and the loader transparently handles either encoding.
    with out.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return out


# ----- 4. Test counts CSV -----------------------------------------------------
def make_test_counts() -> Path:
    """A=機能ID, C=総テスト, D=実施済, E=OK, F=NG (B intentionally blank)."""
    out = OUT_DIR / "test_counts_20260420090000.csv"
    with out.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["機能ID", "", "総テスト", "実施済", "OK", "NG"])
        for fid in UNIQUE_IDS:
            total = random.randint(20, 120)
            # NO_EXEC_FIDS: planned but never executed → 実施済 = 0 so
            # incident_rate for that feature is NaN (divide-by-zero). Any
            # WBS assignee whose sub-tasks land only on these features
            # therefore ends up with avg_incident_rate = NaN, which is
            # the second rendering edge case the bubble map now handles.
            if fid in NO_EXEC_FIDS:
                executed = 0
                ok = 0
                ng = 0
            else:
                executed = random.randint(int(total * 0.4), total)
                ok = random.randint(int(executed * 0.6), executed)
                ng = executed - ok
            writer.writerow([fid, "", total, executed, ok, ng])
    return out


# ----- 5. Code (LoC) xlsx -----------------------------------------------------
def make_code_counts() -> Path:
    wb = Workbook()
    ws = wb.active
    ws.title = "機能ID別サマリ"
    ws["A1"] = "機能ID"
    ws["B1"] = "LoC"
    ws["A1"].font = Font(bold=True)
    ws["B1"].font = Font(bold=True)
    for i, fid in enumerate(UNIQUE_IDS, start=2):
        ws.cell(row=i, column=1, value=fid)
        ws.cell(row=i, column=2, value=random.randint(80, 4500))
    out = OUT_DIR / "code_counts_20260420090000.xlsx"
    wb.save(out)
    return out


def make_roster() -> Path:
    """Write a 担当者一覧 xlsx matching load_roster's expected shape.
    Names overlap with the WBS assignee pool so the Phase-3 roster ⇄
    role-analytics join would hit (even though only Phase 1 is live)."""
    wb = Workbook()
    ws = wb.active
    ws.title = "担当者一覧"
    headers = ["チーム名", "担当者名", "PC貸与数", "専用携帯貸与数",
               "VPNアカウント"]
    for col_idx, h in enumerate(headers, start=1):
        ws.cell(row=1, column=col_idx, value=h).font = Font(bold=True)
    # Echoing the WBS role pool (WBS_ROLE_ASSIGNEES) so names line up
    # with the 担当者×ロール analytics. Mix of team assignments +
    # gear + VPN flag for demo realism.
    seed = [
        ("フロントエンド", "田中", 1, 1, True),
        ("フロントエンド", "佐藤", 1, 0, True),
        ("バックエンド",   "高橋", 1, 1, True),
        ("バックエンド",   "伊藤", 1, 0, False),
        ("QA",             "鈴木", 1, 0, True),
        ("QA",             "小林", 1, 0, False),
        ("インフラ",       "渡辺", 2, 1, True),
        ("インフラ",       "中村", 1, 0, True),
    ]
    for i, row in enumerate(seed, start=2):
        for col_idx, v in enumerate(row, start=1):
            ws.cell(row=i, column=col_idx, value=v)
    for col_idx, width in enumerate([16, 22, 12, 14, 14], start=1):
        ws.column_dimensions[ws.cell(row=1, column=col_idx)
                              .column_letter].width = width
    out = OUT_DIR / "roster.xlsx"
    wb.save(out)
    return out


def make_calendar() -> Path:
    """2-sheet calendar xlsx. Events sheet starts from the main-side
    template (which seeds all 2024–2027 Japanese holidays) and appends
    our demo company events on top. Non-working sheet is hand-rolled so
    the demo names line up with the WBS roster.

    Re-uses main.generate_calendar_template so the sample calendar ships
    the same holiday list as any template a user downloads from the
    dashboard — avoids drift when the base holiday table changes."""
    import sys
    sys.path.insert(0, str(OUT_DIR.parent))
    import main as _app  # noqa: E402

    # Base template (holidays + a few demo events) — write to disk, then
    # reopen to append our non-working rows + customised sample events.
    out = OUT_DIR / "calendar.xlsx"
    out.write_bytes(_app.generate_calendar_template(sample=False))

    # Reopen to add demo events + non-working entries on top of holidays.
    from openpyxl import load_workbook as _load
    wb = _load(out)
    ws_e = wb["イベント"]
    # Append demo events right after the last holiday row.
    next_row = ws_e.max_row + 1
    demo_events = [
        (date(2026, 1, 15), "キックオフMTG",      "全社キックオフ"),
        (date(2026, 3, 15), "Designレビュー",     "中間レビュー+意思決定"),
        (date(2026, 4, 20), "リリース判定会議",   "Goサインの有無確認"),
        (date(2026, 5, 20), "ポストモーテム",     "品質振り返り"),
    ]
    for i, (d, title, desc) in enumerate(demo_events, start=next_row):
        ws_e.cell(row=i, column=1, value=d).number_format = "yyyy-mm-dd"
        ws_e.cell(row=i, column=2, value=title)
        ws_e.cell(row=i, column=3, value=desc)

    # Fill the 非稼働日 sheet (empty in template; we seed realistic rows
    # that match WBS assignee names so the 担当者×ロール demo stays coherent).
    ws_n = wb["非稼働日"]
    nonwork = [
        ("田中", date(2026, 2, 9),  date(2026, 2, 10), "有給"),
        ("佐藤", date(2026, 3, 2),  date(2026, 3, 2),  "半休"),
        ("鈴木", date(2026, 4, 27), date(2026, 5, 1),  "連休+有給"),
        ("高橋", date(2026, 5, 11), date(2026, 5, 15), "夏季休暇"),
        ("小林", date(2026, 3, 23), date(2026, 3, 23), "通院"),
        ("渡辺", date(2026, 4, 6),  date(2026, 4, 6),  "私用"),
    ]
    for i, (name, s, e, reason) in enumerate(nonwork, start=2):
        ws_n.cell(row=i, column=1, value=name)
        ws_n.cell(row=i, column=2, value=s).number_format = "yyyy-mm-dd"
        ws_n.cell(row=i, column=3, value=e).number_format = "yyyy-mm-dd"
        ws_n.cell(row=i, column=4, value=reason)

    wb.save(out)
    return out


# ----- 8. Backlog tickets CSV -------------------------------------------------
# Synthetic Backlog.com export. The real file's 担当者 column holds names like
# `田中太郎` / `田中 太郎` / `田中　太郎` (no-space / ASCII space / full-width
# space) — we mix all three so the loader's normalisation path is exercised.
# Encoding: CP932, line-endings: LF, dates: M/D/YYYY, blanks: literal `""`.
BACKLOG_ASSIGNEES = [
    "田中太郎", "田中 太郎", "田中　太郎",  # 3 variants of the same person
    "佐藤 花子", "鈴木次郎", "高橋　美咲",
    "伊藤 健一", "渡辺　涼", "小林 真理",
    "",  # intentionally unassigned
]
BACKLOG_TYPES = ["リスク", "課題", "作業", "質問"]
BACKLOG_STATUSES = ["未対応", "処理中", "処理済み", "完了"]
BACKLOG_CATEGORIES = [
    "性能", "セキュリティ", "UI/UX", "互換性", "ドキュメント",
    "インフラ", "データ移行", "運用", "",
]
BACKLOG_PHASES = ["要件定義", "基本設計", "詳細設計", "実装",
                   "テスト", "リリース", "運用", ""]
BACKLOG_SUBJECTS = [
    "ログイン画面のレスポンス遅延", "API 仕様書の更新漏れ",
    "本番 DB 接続タイムアウト調査", "管理画面の権限バグ",
    "顧客データ移行手順の確認", "SSL 証明書更新",
    "決済処理のエラーハンドリング強化", "通知メール文面レビュー",
    "帳票出力フォーマットの見直し", "パスワードリセットのフロー改善",
    "監視アラート閾値の調整", "自動テストの追加",
    "ドキュメントの翻訳", "セッションタイムアウト設定",
    "バックアップ復元訓練", "オンプレ → クラウド移行計画",
    "コードレビュー指摘事項の対応", "CI パイプラインの高速化",
    "既存機能のリファクタリング",
]
BACKLOG_DETAILS = [
    "詳細調査中。再現手順を固めてから改修に入る予定。",
    "別部署からの連絡待ち。今週金曜までに回答を得たい。",
    "顧客から改善要望あり。次スプリントで対応方針を決定。",
    "一時対応済み。恒久対応は次フェーズにキャリーオーバー。",
    "現在の設計では対応難。代替案を検討中。",
    "",  # blank detail — realistic for quickly-filed tickets
]


def make_backlog() -> Path:
    """Write a synthetic Backlog.com issue-list CSV.

    Columns (13): キーID / ID / 種別 / 状態 / カテゴリー名 / 件名 / 詳細 /
    担当者 / 開始日 / 期限日 / 更新日 / 発生フェーズ / 顧客共有.
    Kept deliberately broad so the Dashboard's facet filters have
    something to do; a handful of tickets left 状態=完了 and 担当者=""
    to exercise the empty-state / filter-edge cases."""
    out = OUT_DIR / "backlog.csv"
    today = date(2026, 4, 20)
    rows: list[dict[str, str]] = []
    # Start keyIDs at 1001 so they look like realistic Backlog numeric IDs.
    for i in range(35):
        key_id = 1000 + i + 1
        issue_id = f"DEMO-{i+1:03d}"
        ttype = random.choice(BACKLOG_TYPES)
        status = random.choice(BACKLOG_STATUSES)
        cat = random.choice(BACKLOG_CATEGORIES)
        subj = random.choice(BACKLOG_SUBJECTS)
        detail = random.choice(BACKLOG_DETAILS)
        assignee = random.choice(BACKLOG_ASSIGNEES)
        phase = random.choice(BACKLOG_PHASES)
        # 顧客共有: 要 / 不 / blank (~60/30/10 mix)
        share = random.choices(["要", "不", ""], weights=[6, 3, 1])[0]
        # Dates. 開始日 is always set for in-flight items; 期限日 may be
        # missing for open-ended tickets; 更新日 exists for every ticket
        # but can lag up to 30 days behind today.
        start = today - timedelta(days=random.randint(2, 120))
        has_due = random.random() > 0.2
        due = (start + timedelta(days=random.randint(3, 60))
               if has_due else None)
        updated = today - timedelta(days=random.randint(0, 30))
        rows.append({
            "キーID": str(key_id),
            "ID": issue_id,
            "種別": ttype,
            "状態": status,
            "カテゴリー名": cat,
            "件名": subj,
            "詳細": detail,
            "担当者": assignee,
            "開始日": start.strftime("%-m/%-d/%Y"),
            "期限日": due.strftime("%-m/%-d/%Y") if due else "",
            "更新日": updated.strftime("%-m/%-d/%Y"),
            "発生フェーズ": phase,
            "顧客共有": share,
        })

    # Backlog's real export uses CP932 with LF line endings. QUOTE_ALL so
    # commas inside 詳細 never split fields; matches real export behaviour.
    with out.open("w", encoding="cp932", newline="\n",
                   errors="replace") as f:
        writer = csv.DictWriter(
            f, fieldnames=list(rows[0].keys()),
            quoting=csv.QUOTE_ALL, lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)
    return out


def main() -> None:
    print("Generating sample files into", OUT_DIR)
    for path in [
        make_function_master(),
        make_wbs(),
        make_defects(),
        make_test_counts(),
        make_code_counts(),
        make_roster(),
        make_calendar(),
        make_backlog(),
    ]:
        size = path.stat().st_size
        print(f"  {path.name:28s} {size:>8,} bytes")
    print("Done.")


if __name__ == "__main__":
    main()
