"""Generate synthetic sample files for dashboard4dx.

Run this once to (re)create the sample files in this directory:
    python sample_data/generate_samples.py

Filename conventions match real-world inputs:
- Function master / WBS / defect tracker exports: plain filenames (no timestamp).
- Test counts / Code line counts: filenames carry a `_YYYYMMDDhhmmss` snapshot
  stamp because those are auto-generated by tools and the dashboard uses the
  stamp to organize history for trend analysis.

All data is fictional. No real project information is included.
"""
from __future__ import annotations

import csv
import random
from datetime import date, timedelta
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

random.seed(20260420)

OUT_DIR = Path(__file__).resolve().parent

# ----- Function ID master -----------------------------------------------------
# Real-world format: 1–10 ASCII letters + 1–10 ASCII digits, no separators.
# A few IDs intentionally appear twice with different names (the spec allows
# duplicate Function IDs with different Function names).
FUNCTION_ENTRIES: list[tuple[str, str]] = [
    ("AUTH001",  "User Login"),
    ("AUTH002",  "User Registration"),
    ("AUTH003",  "Password Reset"),
    ("USER010",  "Profile Edit"),
    ("USER020",  "Profile Edit (Admin)"),
    ("SEARCH01", "Search (Basic)"),
    ("SEARCH01", "Search (Advanced)"),     # duplicate ID, different name
    ("CART001",  "Cart Add"),
    ("CART002",  "Cart Remove"),
    ("ORD001",   "Checkout"),
    ("PAY001",   "Payment - Credit Card"),
    ("PAY001",   "Payment - Bank Transfer"),  # duplicate ID, different name
    ("ORD010",   "Order History"),
    ("NOTIFY01", "Notification - Email"),
    ("NOTIFY02", "Notification - Push"),
    ("SYNC001",  "Settings Sync"),
    ("EXP001",   "Data Export"),
    ("IMP001",   "Data Import"),
    ("AUDIT01",  "Audit Log"),
    ("ADM001",   "Admin Dashboard"),
]

UNIQUE_IDS = sorted({fid for fid, _ in FUNCTION_ENTRIES})


# ----- 1. Function master xlsx ------------------------------------------------
def make_function_master() -> Path:
    """Build a master xlsx that exercises the loader's tricky cases:
      - Section-header rows (col B filled, col F empty) interspersed in data
      - A trailing 'Total' row (col B filled, col F empty) past the last entry
      - Strike-through formatting on one row (must NOT be excluded)
      - Duplicate Function IDs with different names
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "機能一覧"
    headers = ["No", "Category", "Subsystem", "Owner", "Status",
               "機能ID", "機能名称", "Notes"]
    for col_idx, h in enumerate(headers, start=1):
        ws.cell(row=1, column=col_idx, value=h).font = Font(bold=True)

    # Insert a section header before these IDs (B filled, F empty).
    section_breaks = {"SEARCH01": "--- Search & Discovery ---",
                      "PAY001":   "--- Payment ---"}

    row_cursor = 2
    seq = 1
    for fid, fname in FUNCTION_ENTRIES:
        if fid in section_breaks and not any(
            ws.cell(row=r, column=2).value == section_breaks[fid]
            for r in range(2, row_cursor)
        ):
            # B filled, F empty → loader must skip and continue
            ws.cell(row=row_cursor, column=2, value=section_breaks[fid])
            row_cursor += 1

        ws.cell(row=row_cursor, column=1, value=seq); seq += 1
        ws.cell(row=row_cursor, column=2,
                value=random.choice(["Auth", "User", "Order", "Notify", "Admin"]))
        ws.cell(row=row_cursor, column=3,
                value=random.choice(["Web", "API", "Worker"]))
        ws.cell(row=row_cursor, column=4,
                value=random.choice(["alice", "bob", "carol", "dave"]))
        ws.cell(row=row_cursor, column=5,
                value=random.choice(["Active", "Active", "Active", "Deprecated"]))
        ws.cell(row=row_cursor, column=6, value=fid)
        ws.cell(row=row_cursor, column=7, value=fname)

        if fid == "AUDIT01":
            for col_idx in range(1, 9):
                ws.cell(row=row_cursor, column=col_idx).font = Font(strike=True)
        row_cursor += 1

    # A blank-ish gap, then a trailing 'Total' row (B filled, F empty)
    row_cursor += 2
    ws.cell(row=row_cursor, column=2, value="Total")

    out = OUT_DIR / "function_master.xlsx"
    wb.save(out)
    return out


# ----- 2. WBS xlsm ------------------------------------------------------------
WBS_SUBTASK_LABELS = ["設計", "実装", "単体テスト", "結合テスト", "レビュー"]


def _write_percent(ws, coord: str, pct: int) -> None:
    """Write an Excel percent-formatted cell: underlying value is fractional
    (0..1) and the display format is ``0%``. This matches how real WBS tools
    store progress columns, so the loader's percent-normalization path is
    exercised by the sample too."""
    cell = ws[coord]
    cell.value = pct / 100.0
    cell.number_format = "0%"


def _fmt_md(d):
    """Format a date as ``MM/DD`` — matches the real WBS convention where
    per-task dates omit the year and the phase anchors on row 6 (J6 / N6)
    carry the absolute 年/月/日 so the year can be reconstructed."""
    if d is None:
        return None
    return f"{d.month:02d}/{d.day:02d}"


def make_wbs() -> Path:
    """Build a WBS that mimics the real format: data starts row 16, Function ID
    appears as '機能ID：XXXX' somewhere in cols E–I, key columns at P/Q/R/S/T/U/V/AA.

    Some Function IDs also carry sub-task breakdown rows: rows *without* a
    Function ID where L column is "●" (fixed marker). In those rows the
    column right of the parent's Function ID column holds a task label
    (設計 / 実装 / etc.) and P..V/AA carry that sub-task's own schedule.

    For exercising loader behavior the sample also includes a small number
    of intentionally-skipped shapes:
      - A duplicate Function ID row after its first valid occurrence (should
        be skipped by the loader; by default its following ● rows also skip).
      - A row with no Function ID and no ● in L (a noise / spacer row, also
        skipped — exercises the "●-gated" sub-task filter).
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "メイン"

    # Rows 1-15: arbitrary header / metadata noise
    ws["A1"] = "WBS Sample"
    ws["A2"] = "Generated for dashboard4dx demo"
    # Phase anchors (row 6). Real WBS files store the phase start/end here
    # as 年/月/日; per-task dates (Q/R/S/T) are written later as 月/日 only
    # and the loader resolves the year from this window.
    phase_start = date(2026, 1, 1)
    phase_end = date(2026, 5, 31)
    ws["I6"] = "期間"
    ws["J6"] = phase_start.strftime("%Y/%m/%d")
    ws.merge_cells("J6:L6")
    ws["M6"] = "〜"
    ws["N6"] = phase_end.strftime("%Y/%m/%d")
    ws.merge_cells("N6:O6")
    ws["A14"] = "Section"
    ws["E14"] = "Phase / Function"
    ws["L14"] = "●印"
    ws["P14"] = "予定工数"
    ws["Q14"] = "開始予定日"
    ws["R14"] = "終了予定日"
    ws["S14"] = "開始実績日"
    ws["T14"] = "終了実績日"
    ws["U14"] = "投入工数"
    ws["V14"] = "実績進捗率"
    ws["AA14"] = "計画進捗率"

    # ~40% of Function IDs get sub-task breakdowns so both patterns appear.
    with_subs = set(random.sample(UNIQUE_IDS,
                                  k=max(3, int(len(UNIQUE_IDS) * 0.4))))

    today = date(2026, 4, 20)
    row = 16
    for fid in UNIQUE_IDS:
        # Sprinkle the Function ID across one of cols E..I randomly,
        # using one of three accepted formats. Keep sub-col <= J by capping
        # the parent column at H when we know we'll emit sub-tasks.
        cols = ["E", "F", "G", "H"] if fid in with_subs else ["E", "F", "G", "H", "I"]
        target_col = random.choice(cols)
        sub_col = chr(ord(target_col) + 1)  # column immediately right of parent
        fmt = random.choice([f"機能ID：{fid}", f"機能ID:{fid}", fid])
        ws[f"A{row}"] = "Feature"
        ws[f"{target_col}{row}"] = fmt

        planned_effort = round(random.uniform(5, 40), 1)
        actual_effort = round(planned_effort * random.uniform(0.6, 1.3), 1)
        start_plan = today - timedelta(days=random.randint(20, 80))
        end_plan = start_plan + timedelta(days=random.randint(5, 30))
        start_actual = start_plan + timedelta(days=random.randint(-3, 5))
        # 25% of items are still in flight: no actual end date
        end_actual = (end_plan + timedelta(days=random.randint(-3, 10))
                      if random.random() > 0.25 else None)
        actual_pct = (random.randint(70, 100)
                      if end_actual else random.randint(10, 70))
        planned_pct = random.randint(60, 100)

        ws[f"P{row}"] = planned_effort
        ws[f"Q{row}"] = _fmt_md(start_plan)
        ws[f"R{row}"] = _fmt_md(end_plan)
        ws[f"S{row}"] = _fmt_md(start_actual)
        ws[f"T{row}"] = _fmt_md(end_actual)
        ws[f"U{row}"] = actual_effort
        _write_percent(ws, f"V{row}", actual_pct)
        _write_percent(ws, f"AA{row}", planned_pct)
        row += 1

        if fid not in with_subs:
            continue

        # Emit 2–4 sub-task rows that split the parent's planned window.
        n_subs = random.randint(2, 4)
        subs = random.sample(WBS_SUBTASK_LABELS, k=n_subs)
        total_days = max(n_subs, (end_plan - start_plan).days)
        chunk = total_days // n_subs
        remaining_effort = planned_effort
        remaining_actual = actual_effort
        for i, sub_label in enumerate(subs):
            s_start_plan = start_plan + timedelta(days=i * chunk)
            s_end_plan = (end_plan if i == n_subs - 1
                          else start_plan + timedelta(days=(i + 1) * chunk - 1))
            s_start_actual = s_start_plan + timedelta(days=random.randint(-2, 3))
            # Last sub-task inherits the parent's in-flight status roughly
            in_flight = (end_actual is None and i == n_subs - 1) or random.random() < 0.15
            s_end_actual = (None if in_flight
                            else s_end_plan + timedelta(days=random.randint(-2, 4)))
            share = (1.0 / (n_subs - i)) if i < n_subs - 1 else 1.0
            s_planned_effort = round(remaining_effort * share, 1)
            s_actual_effort = round(remaining_actual * share, 1)
            remaining_effort -= s_planned_effort
            remaining_actual -= s_actual_effort

            ws[f"A{row}"] = "Task"
            ws[f"L{row}"] = "●"
            ws[f"{sub_col}{row}"] = sub_label
            ws[f"P{row}"] = s_planned_effort
            ws[f"Q{row}"] = _fmt_md(s_start_plan)
            ws[f"R{row}"] = _fmt_md(s_end_plan)
            ws[f"S{row}"] = _fmt_md(s_start_actual)
            ws[f"T{row}"] = _fmt_md(s_end_actual)
            ws[f"U{row}"] = s_actual_effort
            _write_percent(ws, f"V{row}",
                           random.randint(70, 100) if s_end_actual
                           else random.randint(10, 70))
            _write_percent(ws, f"AA{row}", random.randint(60, 100))
            row += 1

    # ----- Loader edge-cases ---------------------------------------------------
    # A noise / spacer row with no Function ID and no ● marker. The loader
    # must skip this (sub-task candidacy is gated on L="●").
    ws[f"A{row}"] = "(note)"
    ws[f"F{row}"] = "※ 以下は重複機能IDのテストケース"
    row += 1

    # Duplicate Function ID: AUTH001 appears again well below its first
    # occurrence. The loader keeps only the first; this row and its ● rows
    # below are skipped (default). With the "attach_after_dup" setting ON,
    # the ● rows re-attach to the previously valid parent instead of dying.
    dup_fid = "AUTH001"
    ws[f"A{row}"] = "Feature"
    ws[f"G{row}"] = f"機能ID:{dup_fid}"
    ws[f"P{row}"] = 12.3
    ws[f"Q{row}"] = _fmt_md(date(2026, 4, 15))
    ws[f"R{row}"] = _fmt_md(date(2026, 4, 25))
    ws[f"S{row}"] = _fmt_md(date(2026, 4, 15))
    ws[f"U{row}"] = 8.0
    _write_percent(ws, f"V{row}", 55)
    _write_percent(ws, f"AA{row}", 70)
    row += 1
    for sub in ("追加レビュー", "追加修正"):
        ws[f"A{row}"] = "Task"
        ws[f"L{row}"] = "●"
        ws[f"H{row}"] = sub  # sub_col = G+1 = H
        ws[f"P{row}"] = 6.0
        ws[f"Q{row}"] = _fmt_md(date(2026, 4, 15))
        ws[f"R{row}"] = _fmt_md(date(2026, 4, 20))
        ws[f"S{row}"] = _fmt_md(date(2026, 4, 15))
        ws[f"U{row}"] = 4.0
        _write_percent(ws, f"V{row}", 40)
        _write_percent(ws, f"AA{row}", 60)
        row += 1

    # Save as .xlsm — openpyxl can write the file with a macro-enabled extension
    # even without an actual VBA project; the loader reads it just fine.
    out = OUT_DIR / "wbs.xlsm"
    wb.save(out)
    return out


# ----- 3. Defect tracker CSV --------------------------------------------------
def make_defects() -> Path:
    out = OUT_DIR / "defects.csv"
    trackers = ["不具合管理", "課題管理", "不具合管理", "不具合管理", "タスク"]
    statuses = ["新規", "対応中", "解決", "却下", "再発"]
    classes = ["仕様漏れ", "実装ミス", "設計不備", "環境起因", "再現不可"]
    assignees = ["alice", "bob", "carol", "dave", "ellen"]

    today = date(2026, 4, 20)
    rows = []
    for i in range(80):
        fid = random.choice(UNIQUE_IDS)
        tracker = random.choice(trackers)
        status = random.choice(statuses)
        start = today - timedelta(days=random.randint(1, 120))
        # 35% have no actual end date (unresolved)
        end = (start + timedelta(days=random.randint(1, 30))
               if random.random() > 0.35 else None)
        # Defect tracker exports dates in MM/DD/YYYY (US-style).
        rows.append({
            "トラッカー": tracker,
            "ステータス": status,
            "担当者": random.choice(assignees),
            "実開始日": start.strftime("%m/%d/%Y"),
            "実終了日": end.strftime("%m/%d/%Y") if end else "",
            "機能ID": fid,
            "問題分類": random.choice(classes),
        })

    # Real exports are usually CP932; we write UTF-8 with BOM here for editor
    # convenience, and the loader transparently handles either encoding.
    with out.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return out


# ----- 4. Test counts CSV -----------------------------------------------------
def make_test_counts() -> Path:
    """A=機能ID, C=総テスト, D=実施済, E=OK, F=NG (B intentionally blank)."""
    out = OUT_DIR / "test_counts_20260420090000.csv"
    with out.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["機能ID", "", "総テスト", "実施済", "OK", "NG"])
        for fid in UNIQUE_IDS:
            total = random.randint(20, 120)
            executed = random.randint(int(total * 0.4), total)
            ok = random.randint(int(executed * 0.6), executed)
            ng = executed - ok
            writer.writerow([fid, "", total, executed, ok, ng])
    return out


# ----- 5. Code (LoC) xlsx -----------------------------------------------------
def make_code_counts() -> Path:
    wb = Workbook()
    ws = wb.active
    ws.title = "機能ID別サマリ"
    ws["A1"] = "機能ID"
    ws["B1"] = "LoC"
    ws["A1"].font = Font(bold=True)
    ws["B1"].font = Font(bold=True)
    for i, fid in enumerate(UNIQUE_IDS, start=2):
        ws.cell(row=i, column=1, value=fid)
        ws.cell(row=i, column=2, value=random.randint(80, 4500))
    out = OUT_DIR / "code_counts_20260420090000.xlsx"
    wb.save(out)
    return out


def main() -> None:
    print("Generating sample files into", OUT_DIR)
    for path in [
        make_function_master(),
        make_wbs(),
        make_defects(),
        make_test_counts(),
        make_code_counts(),
    ]:
        size = path.stat().st_size
        print(f"  {path.name:28s} {size:>8,} bytes")
    print("Done.")


if __name__ == "__main__":
    main()
